### ISSUE TITLE
BUG: Emojis missing on Safari when opening the picker for the first time

### ISSUE THREAD

**Issue by arnu515** [nolanlawson/emoji-picker-element#282] opened 2022-05-26 13:22 UTC
The emojis are missing on Safari when opening it for the first time, but closing and reopening the picker fixes the issue

https://user-images.githubusercontent.com/52203828/170496119-a5e6a11c-0017-463c-bf58-10153d6ea2a4.mp4

**Comment by nolanlawson** [comment] 2022-05-27 14:34
Is there an error message somewhere? What version of Safari and what device? (iPad, Mac, iPhone, etc.?)

I've tested the emoji picker on multiple versions of Safari and never seen this issue…

**Comment by arnu515** [comment] 2022-05-28 06:50
Doesn't look like there are any related to the library.

**Comment by arnu515** [comment] 2022-05-28 06:50
> What version of Safari and what device? (iPad, Mac, iPhone, etc.?)

Safari on MacOS monterey

**Comment by nolanlawson** [comment] 2022-05-29 19:44
Sorry, I can't reproduce in Safari 15.4 on MacOS Monterey using [the emoji-picker-element demo site](nolanlawson.github.io/emoji-picker-element/). It seems like this might be something specific to your application. If you can provide any more information, like a live reproducible use case, that would be helpful.

**Comment by nolanlawson** [comment] 2022-12-29 18:36
Closing, please reopen if you have a reduced repro. Thanks!

**Closed by nolanlawson** 2022-12-29 18:36 UTC
Labels: bug
